## Basic Configuration
baseurl = "https://arloor.github.io/"
languageCode = "zh-CN"
hasCJKLanguage = true

title = "八股文"
theme = "hyde-arloor"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
#googleAnalytics = "UA-133187648-1"
enableRobotsTXT = true

summarylength = 50

[pagination]
pagerSize = 10

## Site Settings
[params]
# 取消注释以开启评论
#UtterancesRepo= "arloor/blog"
#tterancesIssueTerm = "pathname"
#UtterancesTheme="github-light"


layoutReverse = false
author = "刘港欢"
title = "八股文"
description = "今天，你学习了吗"
authorimage = "/img/head.jpeg"
#authorimage = "/img/dao.jfif"
dateformat = "Jan 2, 2006"

# sidebar, copyright & license
copyright = "arloor"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
showBuiltWith = true

# https://highlightjs.org
highlightjs = true
highlightjsstyle = "atom-one-dark" # atom-one-dark github default

# please choose either GraphComment or Disqus or Utterances
#GraphCommentId = "..."
#UtterancesRepo = "..." # https://utteranc.es/
#UtterancesIssueTerm = "..." # pathname, url, title, og:title
#UtterancesTheme = "..." # github-light or github-dark

# Table of contents
#toc = none, "hugo", or "tocbot"
toc = "hugo"

[params.meta]
keywords = "刘港欢, arloor, moontell"
description = "今天，你学习了吗"

## Social Accounts
[params.social]
github = "arloor"
#instagram = "<username>"
#xing = "<username>"
#linkedin = "<username>"
twitter = "njulgh"
#facebook = "<username>"
#stackoverflow = "<username>"
telegram = "popstary"
email = "admin@arloor.com"
#gravatar = "admin@arloor.com"

## Main Menu
[[menu.main]]
name = "文章"
weight = 2
identifier = "文章"
url = "/posts/"
[[menu.main]]
name = "分类"
weight = 3
identifier = "分类"
url = "/tags/"
[[menu.main]]
name = "我的博客"
weight = 4
identifier = "我的博客"
url = "https://www.arloor.com"
# [[menu.main]]
# name = "关于我"
# identifier = "关于我"
# weight = 4
# url = "/about/"
# [[menu.main]]
# name = "苏ICP备17024437号"
# weight = 6
# identifier = "苏ICP备17024437号"
# url = "http://beian.miit.gov.cn/"
